### ISSUE TITLE
error while using "indexing_pipe_std.run({"cleaner":{"documents":raw_docs}})"

### ISSUE THREAD

**Issue by QoLM2023** [anakin87/notebooks#1]
It seems that there is no "content" field
WARNING:haystack.preview.components.preprocessors.text_document_cleaner:DocumentCleaner only cleans text documents but document.content for document ID 3afe9639cc1ad1fdbbc2fc176685c40d28ef01415c0d87983559d213db2bb938 is None.
WARNING:haystack.preview.components.preprocessors.text_document_cleaner:DocumentCleaner only cleans text documents but document.content for document ID a49eb903312cd60d8abf5446e4a42ad1dc4c6e7da70a4e3b5a90c3a516f78913 is None.
WARNING:haystack.preview.components.preprocessors.text_document_cleaner:DocumentCleaner only cleans text documents but document.content for document ID 059145f921b090b36adf09f4bf898295a276d65ad3fbd537f4b0455f1b676d4c is None.
WARNING:haystack.preview.components.preprocessors.text_document_cleaner:DocumentCleaner only cleans text documents but document.content for document ID ca8e0d24e5bb4cabb8cceb9af140b4ace194b1b5f2162ddd007874f418e737fa is None.
WARNING:haystack.preview.components.preprocessors.text_document_cleaner:DocumentCleaner only cleans text documents but document.content for document ID ab23fbd4439839b13598a942556752da782634b48e0868c68d2b134f49715735 is None.
-------

**Comment by anakin87** [comment]
Hello, @QoLM2023!

Thanks for reporting this error.

It was due to a change in the Haystack 2.x preview package, which is still experimental and subject to changes.

I have updated the notebook. It is working fine now.

Enjoy your experimentation!

**Comment by QoLM2023** [comment]
Hi,
Oh, that’s make sense as it works fine for me about a week ago.. I will try
now again. Thank you for the fast response!

The haystack 2.preview is part of haystack-ai right?
Is it different from farm haystack?

Thanks again 🙏🏻

**Comment by anakin87** [comment]
farm-haystack is the current haystack package, that also contains the preview features. We release it every month.

haystack-ai only contains the preview features of the upcoming 2.0 release. It is updated frequently and it is the best way to try the new features, while being unstable.

Read more [here](https://github.com/deepset-ai/haystack/discussions/5568).

**Comment by QoLM2023** [comment]
Cool!
Thank you!
